[aliases]
pacup = "sudo pacman -Syu --noconfirm"
pacin = "dotfiles util pacin"
pac_install = "dotfiles util pacin"
pacrm = "sudo pacman -Rns"
pacss = "pacman -Ss"
pacsi = "pacman -Si"
pacqi = "pacman -Qi"
pacql = "pacman -Ql"
pacqo = "pacman -Qo"
pacclean = "sudo pacman -Sc --noconfirm"
pacorph = "pacman -Qdtq"
yayup = "yay -Syu --noconfirm"
yayin = "yay -S --noconfirm"
yayss = "yay -Ss"
yayrm = "yay -Rns --noconfirm"
journalctl-errors = "journalctl -p 3 -xb"
systemctl-list = "systemctl list-units --type=service --state=running"
wifi = "iwconfig"
kde_restart = "sudo systemctl restart sddm"
sysinfo = "fastfetch"
pactree = "pactree"
pacbig = "dotfiles util pacbig"
pacown = "pacman -Qo"
pacfiles = "pacman -Ql"
yayt = "dotfiles util pacin"
mirrorup = "dotfiles util mirrorup"
paci = "dotfiles util paci"
yayi = "dotfiles util yayi"
