[aliases]
pacup = "sudo pacman -Syu --noconfirm"
pacin = "dotfiles util pacin"
pac_install = "dotfiles util pacin"
pacrm = "sudo pacman -Rns"
pacss = "pacman -Ss"
pacsi = "pacman -Si"
pacqi = "pacman -Qi"
pacql = "pacman -Ql"
pacqo = "pacman -Qo"
yayup = "yay -Syu --noconfirm"
yayin = "yay -S --noconfirm"
wifi = "iwconfig"
sysinfo = "fastfetch"
pactree = "pactree"
pacbig = "dotfiles util pacbig"
pacown = "pacman -Qo"
pacfiles = "pacman -Ql"
mirrorup = "dotfiles util mirrorup"
paci = "dotfiles util paci"
yayi = "dotfiles util yayi"
