[window]
padding = { x = 10, y = 10 }
startup_mode = "Maximized"
decorations = "Buttonless"

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
