[general]
import = [
    "~/.config/alacritty/behavior.toml",
    "~/.config/alacritty/theme.toml",
    "~/.config/alacritty/look.toml",
    "~/.config/alacritty/os.toml",
]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
