monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.usb-Creative_Technology_Ltd_Sound_Blaster_GS5_MF8470-01"
      }
    ]
    actions = {
      update-props = {
        device.profile = "output:analog-stereo"
      }
    }
  }
]
