# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 4
    gaps_out = 4
    border_size = 4
    col.active_border = $activeBorderColor rgba(33442266) $activeBorderColor rgba(33442266) $activeBorderColor 35deg
    col.inactive_border = rgba(ffffff15)

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.15
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = yes

    # Workspace switch slide animation
    animation = workspaces, 1, 4, default, slide
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    single_window_aspect_ratio = 9 6
}
