use crate::config::{config_home, home};
use crate::model::ShellManifest;
use std::fs;
use std::path::{Path, PathBuf};

const START: &str = "# >>> zeachco-dotfiles >>>";
const END: &str = "# <<< zeachco-dotfiles <<<";

pub fn generated_path(shell: &str) -> PathBuf {
    config_home().join("dotfiles/generated").join(match shell {
        "fish" => "config.fish",
        _ => "config.sh",
    })
}

pub fn render(shell: &str, manifest: &ShellManifest, repo: &Path) -> Result<String, String> {
    match shell {
        "bash" | "zsh" => Ok(render_posix(manifest, repo)),
        "fish" => Ok(render_fish(manifest, repo)),
        _ => Err(format!("unsupported shell '{shell}'")),
    }
}

fn render_posix(manifest: &ShellManifest, repo: &Path) -> String {
    let mut out = String::from("# Generated by dotfiles; edit manifests/shell.toml instead.\n");
    out.push_str("export DOTFILES_SHELL_LOADED=1\n");
    out.push_str(&format!(
        "export DOT_DIR={}\n",
        sh_quote(&repo.to_string_lossy())
    ));
    for (key, value) in &manifest.env {
        out.push_str(&format!("export {key}={}\n", sh_quote(value)));
    }
    for path in manifest.paths.iter().rev() {
        out.push_str(&format!(
            "export PATH={}:\"$PATH\"\n",
            sh_quote(&expand_home(path))
        ));
    }
    for (name, command) in &manifest.aliases {
        out.push_str(&format!("alias {name}={}\n", sh_quote(command)));
    }
    out.push_str("dotfiles_update() { dotfiles update \"$@\"; }\n");
    out.push_str("update_dotfiles() { dotfiles update \"$@\"; }\n");
    out
}

fn render_fish(manifest: &ShellManifest, repo: &Path) -> String {
    let mut out = String::from("# Generated by dotfiles; edit manifests/shell.toml instead.\n");
    out.push_str("set -gx DOTFILES_SHELL_LOADED 1\n");
    out.push_str(&format!(
        "set -gx DOT_DIR {}\n",
        fish_quote(&repo.to_string_lossy())
    ));
    for (key, value) in &manifest.env {
        out.push_str(&format!("set -gx {key} {}\n", fish_quote(value)));
    }
    if !manifest.paths.is_empty() {
        out.push_str("fish_add_path");
        for path in &manifest.paths {
            out.push(' ');
            out.push_str(&fish_quote(&expand_home(path)));
        }
        out.push('\n');
    }
    for (name, command) in &manifest.aliases {
        let command = command.replace(" && ", "; and ").replace(" || ", "; or ");
        out.push_str(&format!("alias {name} {}\n", fish_quote(&command)));
    }
    out.push_str("function dotfiles_update; dotfiles update $argv; end\n");
    out.push_str("function update_dotfiles; dotfiles update $argv; end\n");
    out
}

pub fn install(shell: &str, rendered: &str) -> Result<Vec<PathBuf>, String> {
    archive_legacy_profiles()?;
    let generated = generated_path(shell);
    if let Some(parent) = generated.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    atomic_write(&generated, rendered)?;
    let mut changed = vec![generated.clone()];
    let source = match shell {
        "fish" => format!(
            "test -f {}; and source {}",
            fish_quote(&generated.to_string_lossy()),
            fish_quote(&generated.to_string_lossy())
        ),
        _ => format!(
            "[ -f {} ] && . {}",
            sh_quote(&generated.to_string_lossy()),
            sh_quote(&generated.to_string_lossy())
        ),
    };
    match shell {
        "fish" => {
            clean_legacy_fish_hook()?;
            let hook = config_home().join("fish/conf.d/zeachco-dotfiles.fish");
            if let Some(parent) = hook.parent() {
                fs::create_dir_all(parent).map_err(|e| e.to_string())?;
            }
            backup_once(&hook)?;
            atomic_write(&hook, &(source + "\n"))?;
            changed.push(hook);
        }
        "zsh" => {
            let hook = home().join(".zshrc");
            update_hook(&hook, &source)?;
            changed.push(hook);
        }
        "bash" => {
            for hook in [home().join(".bashrc"), home().join(".bash_profile")] {
                update_hook(&hook, &source)?;
                changed.push(hook);
            }
        }
        _ => return Err(format!("unsupported shell '{shell}'")),
    }
    Ok(changed)
}

fn archive_legacy_profiles() -> Result<(), String> {
    let legacy_dir = config_home().join("dotfiles/legacy");
    for entry in fs::read_dir(home()).map_err(|e| e.to_string())? {
        let entry = entry.map_err(|e| e.to_string())?;
        let name = entry.file_name().to_string_lossy().into_owned();
        if !name.starts_with(".dotfiles_") || !entry.path().is_file() {
            continue;
        }
        fs::create_dir_all(&legacy_dir).map_err(|e| e.to_string())?;
        let destination = legacy_dir.join(name);
        if destination.exists() {
            fs::remove_file(&destination).map_err(|e| e.to_string())?;
        }
        fs::rename(entry.path(), destination).map_err(|e| e.to_string())?;
    }
    Ok(())
}

fn clean_legacy_fish_hook() -> Result<(), String> {
    let path = config_home().join("fish/config.fish");
    if !path.is_file() {
        return Ok(());
    }
    let old = fs::read_to_string(&path).map_err(|e| e.to_string())?;
    let cleaned = old
        .lines()
        .filter(|line| !line.contains("zeachco-dotfiles"))
        .collect::<Vec<_>>()
        .join("\n");
    if cleaned.len() != old.trim_end_matches('\n').len() {
        backup_once(&path)?;
        atomic_write(&path, &(cleaned + "\n"))?;
    }
    Ok(())
}

fn update_hook(path: &Path, source: &str) -> Result<(), String> {
    let old = fs::read_to_string(path).unwrap_or_default();
    backup_once(path)?;
    let mut result = String::new();
    let mut skipping = false;
    for line in old.lines() {
        if line == START {
            skipping = true;
            continue;
        }
        if line == END {
            skipping = false;
            continue;
        }
        if !skipping && !line.contains("zeachco-dotfiles") {
            result.push_str(line);
            result.push('\n');
        }
    }
    if !result.is_empty() && !result.ends_with("\n\n") {
        result.push('\n');
    }
    result.push_str(START);
    result.push('\n');
    result.push_str(source);
    result.push('\n');
    result.push_str(END);
    result.push('\n');
    atomic_write(path, &result)
}

fn backup_once(path: &Path) -> Result<(), String> {
    if !path.is_file() {
        return Ok(());
    }
    let backup = path.with_extension("dotfiles-backup");
    if !backup.exists() {
        fs::copy(path, &backup).map_err(|e| format!("{}: {e}", backup.display()))?;
    }
    Ok(())
}

fn atomic_write(path: &Path, text: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let temp = path.with_extension("dotfiles.tmp");
    fs::write(&temp, text).map_err(|e| format!("{}: {e}", temp.display()))?;
    fs::rename(&temp, path).map_err(|e| format!("{}: {e}", path.display()))
}

fn sh_quote(value: &str) -> String {
    format!("'{}'", value.replace("'", "'\\''"))
}
fn fish_quote(value: &str) -> String {
    sh_quote(value)
}
fn expand_home(value: &str) -> String {
    value.replace("$HOME", &home().to_string_lossy())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn renders_native_syntax() {
        let mut manifest = ShellManifest::default();
        manifest.env.insert("EDITOR".into(), "nvim".into());
        manifest
            .aliases
            .insert("gs".into(), "git status --short".into());
        let bash = render("bash", &manifest, Path::new("/tmp/dot files")).unwrap();
        let fish = render("fish", &manifest, Path::new("/tmp/dot files")).unwrap();
        assert!(bash.contains("alias gs='git status --short'"));
        assert!(fish.contains("set -gx EDITOR 'nvim'"));
    }
}
